### PR TITLE
Added ERPNext Technical Training Documentation.

### PR DESCRIPTION
**Pull request by Solufyin**
Hello @netchampfaris 
Here, we added ERPNext technical training tutorials step by step development documentation.
http://www.solufy.in/erpnext_tutorials
Thanks.

### CODE REVIEW

**Comment by Solufyin** [comment]
Hello @netchampfaris,

**Comment by barredterra** [comment]
Nice tutorial, @Solufyin ! Thank you for sharing.

Why did you call it "erpnext-technical-training-tutorials"? Maybe that's a little bit too general. To me it looks like two separate tutorials, "how to set up ERPNext for app development" and "how to create a school management app".

**Comment by ddavidebor** [comment]
Waiting on #283 before evaluating merging

**Comment by ddavidebor** [comment]
Tutorial is no loger online

**Comment by ddavidebor** [comment]
Various sections are obsolete, like install

**Comment by Solufyin** [comment]
> Tutorial is no longer online

**Comment by Solufyin** [comment]
@ddavidebor,

Yes. We have new updated document link.
You can refer below link for ERPNext tutorials
http://www.solufy.in/products

Thanks

**Comment by ddavidebor** [comment]
Got that but this PR cannot be merged unless it's content is relevant, this is just some tutorial added out-of-context to the existing documentation

**Pull request closed without merging**
