### PR TITLE
docs: Add contextual translation docs

### PR DESCRIPTION
**Pull request by surajshetty3416**
Screenshot 2020-05-03 at 9 23 09 PM

### CODE REVIEW

**Comment by barredterra** [comment]
After I add context to a translated string in the code, how do I get it to show up in the translation tool?

For example, I change `_("Submit")` in [this file](https://github.com/frappe/frappe/blob/85ef8b6f83def3750f0f623be8ebf6951954261a/frappe/templates/includes/comments/comments.html#L47) to `_("Submit", context="Leave a Comment")`. What do I need to do for the context to show up in the Translation Tool?

@surajshetty3416

**Comment by surajshetty3416** [comment]
@barredterra Source Text in the Translation Tool is served from the Translation server and not from the local. The context will show up once "`_("Submit", context="Leave a Comment")`" is merged to the source code and the translation server extracts it from the code.

If you want to have the translation for that context in your local, you can use Translation doctype.

**Example:**
Screenshot 2020-05-13 at 8 33 05 PM

**Comment by barredterra** [comment]
Okay, thanks. So it would not work for custom apps / server script, right?

**Comment by surajshetty3416** [comment]
> Okay, thanks. So it would not work for custom apps / server script, right?

Contextual Translation will work for custom apps if you directly create a Translation document for it
**Note**: Translation tool only shows source texts from Frappe & ERPNext app.

**Comment by LarryStar88** [comment]
> @barredterra Source Text in the Translation Tool is served from the Translation server and not from the local. The context will show up once "`_("Submit", context="Leave a Comment")`" is merged to the source code and the translation server extracts it from the code.
> 
> If you want to have the translation for that context in your local, you can use Translation doctype.
> 
> **Example:** Screenshot 2020-05-13 at 8 33 05 PM

Hi @surajshetty3416 but I can't find the context translation functionality locally.

My version:
ERPNext: v13.12.1 (version-13)
Frappe Framework: v13.12.1 (version-13)

Is this feature present on another release? 
let me know? Thanks.

**Pull request merged**
