### PR TITLE
docs: override whitelisted methods

### PR DESCRIPTION
**Pull request by Alchez**
Documentation for https://github.com/frappe/frappe/pull/10549.

### CODE REVIEW

**Comment by surajshetty3416** [comment]
@Alchez Please resolve the conflicts.

**Comment by Alchez** [comment]
@surajshetty3416, the `docs` folder seems to have been removed from the app. Where do you want me to put it now? :sweat_smile:

**Comment by surajshetty3416** [comment]
@Alchez Frappe docs have been moved to [frappe_docs](https://github.com/frappe/frappe_docs). Please raise PR there.

**Comment by Alchez** [comment]
Moved to https://github.com/frappe/frappe_docs/pull/6.

**Pull request closed without merging**
